#
# Copyright (c) 2019-2020. TIBCO Software Inc.
# This file is subject to the license terms contained in the license file that is distributed with this file.
#

#External service  for FraudDetection application
---
kind: Service
apiVersion: v1
metadata:
  name: "befdservice"
spec:
  selector:
    name: "beinferenceagent"
  ports:
    - protocol: "TCP"
      port: 8108
  type: NodePort
---
