---
applications:
- name: ftlmysqlcache
  env:
    PU: cache
    FTL/REALM_SERVER: <REALM_URL>
    BACKINGSTORE_JDBC_URL: <JDBC_URL>
  docker:
    image: <DOCKER_IMAGE>
  routes:
  - route: ftlmysqlcache.apps.internal
  processes:
  - type: web
    instances: 1
    memory: 1G
    disk_quota: 1024M
    health-check-type: process
- name: ftlmysqldefault
  env:
    FTL/REALM_SERVER: <REALM_URL>
    BACKINGSTORE_JDBC_URL: <JDBC_URL>
  docker:
    image: <DOCKER_IMAGE>
  processes:
  - type: web
    instances: 1
    memory: 1G
    disk_quota: 1024M
    health-check-type: process