#
# Copyright (c) 2019-2020. TIBCO Software Inc.
# This file is subject to the license terms contained in the license file that is distributed with this file.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: berms
spec:
  replicas: 1
  selector:
    matchLabels:
      dep_name: "berms-label"
  template:
    metadata:
      labels:
        dep_name: "berms-label"
    spec:
      containers:
      - name: berms-container
        image: "rms:v01"
        env:
        - name: PU
          value: "default"
        - name: COMPONENT
          value: "rms"
        resources:
          requests:
            memory: 700Mi
        volumeMounts:
        - mountPath: "/opt/tibco/be/5.6/rms/shared/"
          name: shared
        - mountPath: "/opt/tibco/be/5.6/rms/config/security/"
          name: security
        - mountPath: "/opt/tibco/be/5.6/examples/standard/WebStudio/"
          name: webstudio
        - mountPath: "/opt/tibco/be/5.6/rms/config/notify/"
          name: notify
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: security
          persistentVolumeClaim:
            claimName: security-pvc
        - name: webstudio
          persistentVolumeClaim:
            claimName: webstudio-pvc
        - name: notify
          persistentVolumeClaim:
            claimName: notify-pvc
