#
# Copyright (c) 2019-2020. TIBCO Software Inc.
# This file is subject to the license terms contained in the license file that is distributed with this file.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: berms
spec:
  replicas: 1
  selector:
    matchLabels:
      dep_name: "berms-label"
  template:
    metadata:
      labels:
        dep_name: "berms-label"
    spec:
      containers:
      - name: berms-container
        image: <RMS Image>
        imagePullPolicy: Always
        env:
        - name: PU
          value: "default"
        - name: COMPONENT
          value: "rms"
        volumeMounts:
        - mountPath: "/opt/tibco/be/5.6/rms/shared/"
          name: shared
        - mountPath: "/opt/tibco/be/5.6/rms/config/security/"
          name: security
        - mountPath: "/opt/tibco/be/5.6/examples/standard/WebStudio/"
          name: webstudio
        - mountPath: "/opt/tibco/be/5.6/rms/config/notify/"
          name: notify
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: efs-shared
        - name: security
          persistentVolumeClaim:
            claimName: efs-security
        - name: webstudio
          persistentVolumeClaim:
            claimName: efs-webstudio
        - name: notify
          persistentVolumeClaim:
            claimName: efs-notify

