#
# Copyright (c) 2019-2020. TIBCO Software Inc.
# This file is subject to the license terms contained in the license file that is distributed with this file.
#
#
# TIBCO BusinessEvents Dockerfile-teagent_fromtar
#
FROM docker.io/library/ubuntu:20.04
MAINTAINER Tibco Software Inc tsi@tibco.com

ARG BE_PRODUCT_VERSION
ARG BE_SHORT_VERSION
ARG BE_PRODUCT_IMAGE_VERSION
ARG DOCKERFILE_NAME
ARG JRE_VERSION

LABEL "TIBCO BusinessEvents Version"=$BE_PRODUCT_VERSION \
      "TIBCO BusinessEvents Docker Image Version"=$BE_PRODUCT_IMAGE_VERSION

RUN apt-get update -y \
 && apt-get upgrade python3-setuptools -y &&  apt-get install --no-install-recommends apt-transport-https curl software-properties-common gnupg-agent ca-certificates python3 python3-pip -y \
 && pip3 install jsonpickle requests awscli boto boto3 botocore \
 && curl -fsSL https://download.docker.com/linux/ubuntu/gpg |  apt-key add - \
 && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable" \
 && apt-get update -y  \ 
 && apt-get install --no-install-recommends docker-ce jq -y \
 && curl -L git.io/weave -o /usr/local/bin/weave \
 && chmod a+x /usr/local/bin/weave \
 && apt-get remove curl -y \
 && rm -rf /var/lib/apt/lists/*

ADD be.tar /opt/tibco

COPY lib/run /opt/tibco/be/${BE_SHORT_VERSION}/cloud/docker/lib/
COPY lib/*.pm lib/*.py lib/*.sh /home/tibco/be/

WORKDIR /home/tibco/be
RUN sed "s/%%%BE_VERSION%%%/${BE_SHORT_VERSION}/" /opt/tibco/be/${BE_SHORT_VERSION}/cloud/docker/lib/run > ./run \
 && chmod +x run

WORKDIR /opt/tibco/be/${BE_SHORT_VERSION}/bin/
WORKDIR /opt/tibco/be/${BE_SHORT_VERSION}/bin/
RUN echo "java.property.com.sun.management.jmxremote.rmi.port=%jmx_port%" >> be-engine.tra

ENV PU=default \
 ENGINE_NAME=be-engine \
 LOG_LEVEL=na \
 DOCKER_HOST=localhost \
 TIBCO_HOME=/opt/tibco \
 BE_HOME=/opt/tibco/be/${BE_SHORT_VERSION} \
 JRE_VERSION=${JRE_VERSION} \
 JRE_HOME=/opt/tibco/tibcojre64/${JRE_VERSION} \
 BE_PRODUCT_VERSION=${BE_PRODUCT_VERSION} \
 COMPONENT=tea \
 BE_TEA_AGENT_AUTO_REGISTER_ENABLE=false \
 BE_TEA_AGENT_MONITORING_ONLY=true \
 TEA_SERVER_URL="http://localhost:8777" \
 TEA_SERVER_USERNAME=admin \
 TEA_SERVER_PASSWORD=admin \
 BE_INSTANCE_DISCOVERY_TYPE=k8s \
 BE_INSTANCE_POLLAR_INTERVAL=30 

RUN mkdir -p /mnt/tibco/be/logs \
 && mkdir -p /mnt/tibco/be/data-store \
 && ln -s /opt/tibco/be/${BE_SHORT_VERSION} /opt/tibco/be/latest

#Logs
VOLUME /mnt/tibco/be/ \
 /opt/tibco/be/${BE_SHORT_VERSION}/teagent/logs/

# JMX Port
EXPOSE 5555

WORKDIR /home/tibco/be
RUN chmod +x *.py
CMD ["./run"]

