#
# Copyright (c) 2019-2020. TIBCO Software Inc.
# This file is subject to the license terms contained in the license file that is distributed with this file.
#
#
# BusinessEvents Dockerfile-teagent
#
ARG BE_PRODUCT_VERSION
ARG BE_SHORT_VERSION
ARG BE_PRODUCT_IMAGE_VERSION
ARG JRE_VERSION
ARG OPEN_JDK_FILENAME

FROM docker.io/library/ubuntu:20.04 as intermediate

ARG BE_PRODUCT_VERSION
ARG BE_SHORT_VERSION
ARG BE_PRODUCT_IMAGE_VERSION
ARG BE_PRODUCT_ADDONS
ARG BE_PRODUCT_HOTFIX
ARG JRE_VERSION
ARG OPEN_JDK_FILENAME
ARG DEBIAN_FRONTEND=noninteractive

LABEL be-intermediate-image=true

RUN apt-get update \
 && apt-get install -y unzip procps findutils hostname tar

COPY lib/*.pm lib/*.py lib/*.sh installers/* lib/run lib/deletelist.txt  /home/tibco/be/

ENV TIBCO_HOME=/opt/tibco \
 BE_HOME=/opt/tibco/be/${BE_SHORT_VERSION} \
 JRE_VERSION=${JRE_VERSION} \
 BE_PRODUCT_VERSION=${BE_PRODUCT_VERSION} \
 COMPONENT=tea

WORKDIR /home/tibco/be
RUN chmod +x *.sh *.pm && chmod +x *.py run
RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_be('$BE_PRODUCT_VERSION','enterprise','na','$BE_PRODUCT_HOTFIX','na','na')"
RUN perl -I. -Mbe_docker_install -e "be_docker_install::replaceRunbeVersionToken('$BE_PRODUCT_VERSION','./run')"
RUN perl -I. -Mbe_docker_install -e "be_docker_install::generateAnnotationIndexes('/opt/tibco/be/${BE_SHORT_VERSION}', '/opt/tibco/tibcojre64/${JRE_VERSION}')" \
 && rm -rf as_installers be_installers *.zip

RUN ./prepare_finalimage.sh

RUN chgrp -R 0 /tibco_home && chmod -R g=u /tibco_home \
    && chgrp -R 0 /home/tibco && chmod -R g=u /home/tibco

RUN mkdir -p /mnt/tibco/be/logs \
 && mkdir -p /mnt/tibco/be/data-store \
 && chgrp -R 0 /mnt/tibco/ \
 && chmod -R g=u /mnt/tibco/

#Discard intermediate image and just copy the installation to a new image.
FROM ubuntu:20.04

RUN apt-get update -y \
 && apt-get upgrade python3-setuptools -y &&  apt-get install --no-install-recommends apt-transport-https curl software-properties-common gnupg-agent ca-certificates python3 python3-pip -y \
 && pip3 install jsonpickle requests awscli boto boto3 botocore \
 && apt-get install --install-suggests jq -y \
 && rm -rf /var/lib/apt/lists/* 
 
ARG BE_PRODUCT_VERSION
ARG BE_SHORT_VERSION
ARG BE_PRODUCT_IMAGE_VERSION
ARG JRE_VERSION

COPY --from=intermediate /home/tibco /home/tibco

COPY --from=intermediate /tibco_home /opt/tibco

COPY --from=intermediate /mnt/tibco /mnt/tibco

LABEL "TIBCO BusinessEvents Version"=$BE_PRODUCT_VERSION \
      "TIBCO BusinessEvents Docker Image Version"=$BE_PRODUCT_IMAGE_VERSION

ENV PU=default \
 ENGINE_NAME=be-engine \
 LOG_LEVEL=na \
 TIBCO_HOME=/opt/tibco \
 BE_HOME=/opt/tibco/be/${BE_SHORT_VERSION} \
 JRE_VERSION=${JRE_VERSION} \
 BE_PRODUCT_VERSION=${BE_PRODUCT_VERSION} \
 COMPONENT=tea \
 BE_TEA_AGENT_AUTO_REGISTER_ENABLE=false \
 BE_TEA_AGENT_MONITORING_ONLY=true \
 TEA_SERVER_URL="http://localhost:8777" \
 TEA_SERVER_USERNAME=admin \
 TEA_SERVER_PASSWORD=admin \
 BE_INSTANCE_DISCOVERY_TYPE=k8s \
 BE_INSTANCE_POLLAR_INTERVAL=30 

RUN ln -s /opt/tibco/be/${BE_SHORT_VERSION} /opt/tibco/be/latest

#Logs, data-store and RMS volumes
VOLUME /mnt/tibco/be/ \
 /opt/tibco/be/${BE_SHORT_VERSION}/teagent/logs/

# JMX Port
EXPOSE 5555

WORKDIR /home/tibco/be

CMD ["./run"]
