#
# Copyright (c) 2019-2020. TIBCO Software Inc.
# This file is subject to the license terms contained in the license file that is distributed with this file.
#
#
# TIBCO BusinessEvents Dockerfile-teagent_fromtar
#
ARG PYTHON_VERSION

FROM docker.io/library/ubuntu:20.04 AS intermediate
MAINTAINER Tibco Software Inc tsi@tibco.com

ARG BE_PRODUCT_VERSION
ARG BE_SHORT_VERSION
ARG BE_PRODUCT_IMAGE_VERSION
ARG JRE_VERSION

LABEL be-intermediate-image=true

ADD be.tar /opt/tibco

COPY lib/run /opt/tibco/be/${BE_SHORT_VERSION}/cloud/docker/lib/
COPY lib/*.pm lib/*.py lib/*.sh /home/tibco/be/

WORKDIR /home/tibco/be
RUN sed "s/%%%BE_VERSION%%%/${BE_SHORT_VERSION}/" /opt/tibco/be/${BE_SHORT_VERSION}/cloud/docker/lib/run > ./run \
 && chmod +x run && chmod +x *.py

RUN mkdir -p /mnt/tibco/be/logs \ 
 && mkdir -p /mnt/tibco/be/data-store

RUN chgrp -R 0 /home/tibco/ \
 && chmod -R g=u /home/tibco/ \
 && chgrp -R 0 /opt/tibco/ \
 && chmod -R g=u /opt/tibco/ \
 && chgrp -R 0 /mnt/tibco/ \
 && chmod -R g=u /mnt/tibco/
 
#Discard intermediate image and just copy the installation to a new image.
FROM ubuntu:20.04 AS image_with_python3

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y \
 && apt-get upgrade python3-setuptools -y &&  apt-get install --no-install-recommends apt-transport-https curl software-properties-common gnupg-agent ca-certificates python3 python3-pip -y \
 && pip3 install jsonpickle requests awscli boto boto3 botocore \
 && apt-get install --install-suggests jq -y \
 && update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
 && rm -rf /var/lib/apt/lists/* 

FROM ubuntu:20.04 AS image_with_python2

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y \
 && apt install curl python2-minimal -y \
 && apt-get upgrade python3-setuptools -y &&  apt-get install --no-install-recommends apt-transport-https curl software-properties-common gnupg-agent ca-certificates python3 python3-pip -y \
 && pip3 install jsonpickle requests awscli boto boto3 botocore \
 && apt-get install --install-suggests jq -y \
 && update-alternatives --install /usr/bin/python python /usr/bin/python2 1 \
 && curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py \
 && python2 get-pip.py \
 && pip install requests jsonpickle

FROM image_with_${PYTHON_VERSION} AS final

ARG BE_PRODUCT_VERSION
ARG BE_SHORT_VERSION
ARG BE_PRODUCT_IMAGE_VERSION
ARG JRE_VERSION
ARG DEBIAN_FRONTEND=noninteractive

COPY --from=intermediate /home/tibco /home/tibco

COPY --from=intermediate /opt/tibco /opt/tibco

COPY --from=intermediate /mnt/tibco /mnt/tibco

LABEL "TIBCO BusinessEvents Version"=$BE_PRODUCT_VERSION \
      "TIBCO BusinessEvents Docker Image Version"=$BE_PRODUCT_IMAGE_VERSION

ENV PU=default \
 ENGINE_NAME=be-engine \
 LOG_LEVEL=na \
 DOCKER_HOST=localhost \
 TIBCO_HOME=/opt/tibco \
 BE_HOME=/opt/tibco/be/${BE_SHORT_VERSION} \
 JRE_VERSION=${JRE_VERSION} \
 BE_PRODUCT_VERSION=${BE_PRODUCT_VERSION} \
 COMPONENT=tea \
 BE_TEA_AGENT_AUTO_REGISTER_ENABLE=false \
 BE_TEA_AGENT_MONITORING_ONLY=true \
 TEA_SERVER_URL="http://localhost:8777" \
 TEA_SERVER_USERNAME=admin \
 TEA_SERVER_PASSWORD=admin \
 BE_INSTANCE_DISCOVERY_TYPE=k8s \
 BE_INSTANCE_POLLAR_INTERVAL=30 \
 JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"

RUN ln -s /opt/tibco/be/${BE_SHORT_VERSION} /opt/tibco/be/latest

#Logs
VOLUME /mnt/tibco/be/ \
 /opt/tibco/be/${BE_SHORT_VERSION}/teagent/logs/

# JMX Port
EXPOSE 5555

WORKDIR /home/tibco/be

CMD ["./run"]
