#
# Copyright (c) 2019-2020. TIBCO Software Inc.
# This file is subject to the license terms contained in the license file that is distributed with this file.
#
#
# TIBCO BusinessEvents Dockerfile-rms_fromtar
#
FROM docker.io/library/ubuntu:20.04
MAINTAINER Tibco Software Inc tsi@tibco.com

ARG BE_PRODUCT_VERSION
ARG BE_SHORT_VERSION
ARG BE_PRODUCT_IMAGE_VERSION
ARG JRE_VERSION
ARG GVPROVIDER
ARG CDD_FILE_NAME
ARG EAR_FILE_NAME

LABEL "TIBCO BusinessEvents Version"=$BE_PRODUCT_VERSION \
      "TIBCO BusinessEvents Docker Image Version"=$BE_PRODUCT_IMAGE_VERSION

ADD be.tar /opt/tibco
COPY gvproviders /home/tibco/be/gvproviders

COPY lib/run /opt/tibco/be/${BE_SHORT_VERSION}/cloud/docker/lib/
COPY lib/*.pm lib/*.sh /home/tibco/be/

WORKDIR /home/tibco/be
RUN sed "s/%%%BE_VERSION%%%/${BE_SHORT_VERSION}/" /opt/tibco/be/${BE_SHORT_VERSION}/cloud/docker/lib/run > ./run \
 && chmod +x run

ENV PU=default \
 ENGINE_NAME=be-engine \
 LOG_LEVEL=na \
 AS_DISCOVER_URL=self \
 AS_PROXY_NODE=false \
 TIBCO_HOME=/opt/tibco \
 BE_HOME=/opt/tibco/be/${BE_SHORT_VERSION} \
 AS_VERSION=${AS_VERSION} \
 JRE_VERSION=${JRE_VERSION} \
 BE_PRODUCT_VERSION=${BE_PRODUCT_VERSION}  \
 CDD_FILE=/opt/tibco/be/${BE_SHORT_VERSION}/rms/bin/${CDD_FILE_NAME} \
 EAR_FILE=/opt/tibco/be/${BE_SHORT_VERSION}/rms/bin/${EAR_FILE_NAME} \
 COMPONENT=rms


# Setup gv providers
RUN chmod +x /home/tibco/be/gvproviders/*.sh && /home/tibco/be/gvproviders/setup.sh ${GVPROVIDER}

RUN mkdir -p /mnt/tibco/be/logs \ 
 && mkdir -p /mnt/tibco/be/data-store \
 && ln -s /opt/tibco/be/${BE_SHORT_VERSION} /opt/tibco/be/latest \
 && chgrp -R 0 /home/tibco/ \
 && chmod -R g=u /home/tibco/ \
 && chgrp -R 0 /opt/tibco/ \
 && chmod -R g=u /opt/tibco/ \
 && chgrp -R 0 /mnt/tibco/ \
 && chmod -R g=u /mnt/tibco/

#Logs, data-store and RMS volumes
VOLUME /mnt/tibco/be/logs \
 /mnt/tibco/be/data-store \
 /opt/tibco/be/${BE_SHORT_VERSION}/rms/config/security \
 /opt/tibco/be/${BE_SHORT_VERSION}/examples/standard/WebStudio \
 /opt/tibco/be/${BE_SHORT_VERSION}/rms/config/notify \
 /opt/tibco/be/${BE_SHORT_VERSION}/rms/shared \
 /opt/tibco/be/${BE_SHORT_VERSION}/rms/locale

# These will always be the listen port for AS and AS Remote URL #5555 for JMX port # 8090 5000 for RMS
EXPOSE 50000 50001 5555 8090 5000

WORKDIR /home/tibco/be

CMD ["./run"]
