{{- range $i, $agent := .Values.agents }}
{{- if gt (int $agent.replicas) 0 }}
{{- $ssName := (printf "%s-%s" $.Release.Name $agent.name) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $ssName }}
spec:
  replicas: {{ $agent.replicas }}
  selector:
    matchLabels:
      name: {{ $ssName }}
  serviceName: {{ include "bechart.discoveryservice.name" $ }}
  template:
    metadata:
      labels:
        name: {{ $ssName }}
        {{- if $agent.cacheStorageEnabled }}
        cacheagent: "yes"
        {{- end }}
    spec:
{{ include "pullsecrets" $ | trim | indent 6 }}
      {{- if eq $.Values.cmType "ignite"}}
      serviceAccount: {{ $.Release.Name }}-ignite
      {{- end }}
{{- if $.Values.podAntiAffinity }}
{{ include "bechart.affinity" $ssName | trim | indent 6 }}
{{- end }}
      containers:
      - name: {{ $agent.name }}-container
        image: {{ $.Values.image }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        {{- if or (not (empty $.Values.envVarsFromConfigMaps)) (not (empty $.Values.envVarsFromSecrets)) (not (empty $.Values.configs)) }}
        envFrom:
        {{- if $.Values.configs }}
        - configMapRef:
            name: {{ $.Release.Name }}-configmap
        {{- end}}
        {{- range $configMapName := $.Values.envVarsFromConfigMaps }}
        - configMapRef:
            name: {{ $configMapName }}
        {{- end }}
        {{- range $secretName := $.Values.envVarsFromSecrets }}
        - secretRef:
            name: {{ $secretName }}
        {{- end }}
        {{- end }}
        env:
        - name: PU
          value: {{ $agent.PU }}
        - name: ENGINE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        {{- range $envKey, $envVal := $.Values.envVars }}
        - name: {{ $envKey }}
          value: {{ $envVal }}
        {{- end}}
{{ include "bechart.discovery.env" $ | trim | indent 8 }}
        {{- if and (not (empty $.Values.mysql.backingstoreUrlGV)) $.Values.mysql.enabled }}
        - name: {{ $.Values.mysql.backingstoreUrlGV }}
          value: "jdbc:mysql://{{ $.Release.Name }}-mysql:3306/{{ $.Values.mysql.auth.database }}"
        {{- end }}
        {{- if $.Values.influxdb.enabled }}
        - name: {{ $.Values.influxdb.influxdbUrlGV }}
          value: "http://{{ $.Release.Name }}-influxdb:8086"
        {{- end }}
{{ include "bechart.resourceLimits" $agent | trim | indent 8 }}
{{ include "healthcheck" $ | trim | indent 8 }}
{{ include "bechart.volumeMounts" $ | trim | indent 8 }}
{{- if $.Values.persistence.scSupportsReadWriteMany }}
{{ include "bechart.volumes" $ | trim | indent 6 }}
{{- else }}
{{ include "bechart.volumeClaimTemplates" $ | trim | indent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
