#
# Copyright (c) 2019-2020. TIBCO Software Inc.
# This file is subject to the license terms contained in the license file that is distributed with this file.
#
{{- if or (eq .Values.cmType "as2" ) (eq .Values.cmType "ftl" ) (eq .Values.cmType "unclustered" ) (eq .Values.cmType "ignite" ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "beservice.fullname" . }}
spec:
  ports:
    - port: {{ .Values.beservice.ports.port }}
      protocol: TCP
  selector:
    name: {{ include "beinferenceagent.fullname" . }}
  type: {{ .Values.beservice.type }}
{{- end }}