{{- if .Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    name: {{ .Release.Name }}-configmap
data:
{{- range $key, $val := .Values.configs }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
