{{- if .Values.apispecservice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-http-service
spec:
  ports:
    - port: {{ .Values.apispecservice.port | default "8180" }}
      protocol: TCP
  selector:
    implicithttpserver: "yes"
  type: {{ .Values.apispecservice.type }}
---
{{- end }}
