{{- if and (eq .Values.bsType "sharednothing") (eq .Values.volumes.pvProvisioningMode "static") (eq .Values.cpType "aws") }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-be-pvc-{{ .Values.volumes.snmountVolume }}"
spec:
  storageClassName: "{{ include "storageclassname" . | trim }}"
  accessModes: 
    - {{ .Values.volumes.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volumes.storage }}
{{- end -}}


{{- if and (eq .Values.mountLogs true) (eq .Values.volumes.pvProvisioningMode "static") (eq .Values.cpType "aws") }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-be-pvc-{{ .Values.volumes.logmountVolume }}"
spec:
  storageClassName: "{{ include "storageclassname" . | trim }}"
  accessModes: 
    - {{ .Values.volumes.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volumes.storage }}
{{- end -}}


{{- if and (eq .Values.rms.enabled true) (eq .Values.volumes.pvProvisioningMode "static") }}
{{- $scName  :=  .Values.volumes.storageClass -}}
{{- $scStorage  :=  .Values.volumes.storage -}}
{{- $accessmodes:= .Values.volumes.accessModes -}}
{{- $releasename:= .Release.Name  -}}
{{- $storageclass:= include "storageclassname" . | trim  -}}
{{- $rmsname:= include "berms.fullname" . | trim -}}
{{- $pvProvisioningMode := .Values.volumes.pvProvisioningMode -}}
{{- $root := . -}}
{{- range tuple "security" "notify" "webstudio" "shared" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "rms-pvc-{{.}}-{{ $rmsname }}-0"
spec:  
  storageClassName: "{{ $storageclass }}"
  accessModes:
    - {{ $accessmodes }}
  resources:
    requests:
      storage: {{ $scStorage }}
{{- end }}
{{- end -}}


{{- if and ( eq .Values.rms.persistenceType "sharednothing" ) (eq .Values.volumes.pvProvisioningMode "static") ( eq .Values.rms.enabled true ) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-rms-pvc-{{ .Values.volumes.snmountVolume }}"
spec:
  storageClassName: "{{ include "storageclassname" . | trim }}"
  accessModes: 
    - {{ .Values.volumes.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volumes.storage }}
{{- end -}}


{{- if and ( eq .Values.mountLogs true ) (eq .Values.volumes.pvProvisioningMode "static") ( eq .Values.rms.enabled true ) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-rms-pvc-{{ .Values.volumes.logmountVolume }}"
spec:
  storageClassName: "{{ include "storageclassname" . | trim }}"
  accessModes: 
    - {{ .Values.volumes.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volumes.storage }}
{{- end -}}

{{- if and ( eq .Values.mountLogs true ) ( eq .Values.tea.enabled true ) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-tea-pvc-{{ .Values.volumes.logmountVolume }}"
spec:
  storageClassName: "{{ include "storageclassname" . | trim }}"
  accessModes: 
    - {{ .Values.volumes.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volumes.storage }}
{{- end -}}