{{- range $i, $agent := .Values.agents }}
{{- if gt (int $agent.replicas) 0 }}
{{- $ssName := (printf "%s-%s" $.Release.Name $agent.name) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $ssName }}-headless
spec:
  selector:
    name: {{ $ssName }}
  type: ClusterIP
  clusterIP: None
  ports:
  {{- if eq $.Values.cmType "as2" }}
    - port: 50000
      protocol: TCP
  {{- end }}
  {{- if or (eq $.Values.cmType "ftl" )  (eq $.Values.cmType "ignite" ) }}
  {{- range $key, $port := $.Values.ignitePort }}
    - port: {{ $port }}
      name: {{ $key }}
      protocol: TCP
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}