#!/bin/bash
#Copyright © 2019. TIBCO Software Inc.
cat <<EOF
Openshift's Source-to-Image (S2I) is a framework for building reproducible container images making it super easy for developers to provide application source code as an input and produce a new image that runs the assembled application as output.

TIBCO Business Events's S2I support allows users to create a reusable builder image while the developer can provide end application source code (via ear & cdd) to create and run the assembled image.

Follow the given steps to use S2I for deploying applications:

Clone https://github.com/TIBCOSoftware/be-tools.git using git clone command on your local machine.
Open terminal and go to folder cloud/docker/s2i


Lets start off with creating a reusable builder image:
./create_builder_image.sh -l <installers-location> -v <BE-version> -i <image-version>

where
[-l|--installers-location]  :       Location where TIBCO BusinessEvents and TIBCO Activespaces installers are located [required]
[-v|--version]              :       TIBCO BusinessEvents product version (3 part number) [required]
[-i|--image-version]        :       Version|tag to be given to the image ('v01' for example) [required]
[-a|--addons]               :       Comma separated values for required addons : process|views [optional]
[--hf]                      :       Additional TIBCO BusinessEvents hotfix version ('1' for example) [optional]"
[--as-hf]                   :       Additional TIBCO ActiveSpaces hotfix version ('1' for example) [optional]"
[-d|--docker-file]          :       Dockerfile to be used for generating image.(default Dockerfile) [optional]"


For example:
./create_builder_image.sh -l /Users/test/BE_Installers -v 5.6.0 -i v01

Next we provide application source to s2i to create an assembled image off the previously created builder image.

s2i build <location of the source code> <name of the builder image> <name of the application image>

Using FraudDetection application for this example,
s2i build /Users/test/Applications/FraudDetection/source com.tibco.be:5.6.0-v01 fdopenshifts2i:01

Finally run the application,
docker run -p 8108:8108 <app-image>

EOF
