name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Helm Chart Testing
    # You may pin to the exact commit or the version.
    # uses: helm/chart-testing-action@5f16c27cf7a4fa9c776ff73734df3909b2b65127
      uses: helm/chart-testing-action@v2.1.0
      with:
        # The chart-testing version to install (default: v3.4.0)
        version: v3.4.0 # optional, default is v3.4.0
        
    - name: setup
      run: |
            pwd
            ls
            cd cloud/kubernetes/helm
            helm dep up
            cd ../tests/template
            go test -v ./...
