name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 30 5 * * 1        #This cron is scheduled to run once in a week on Every Monday 11AM IST

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
        
    - name: Install Helm
      run: |
          sudo apt-get update -y 
          sudo apt-get install wget tar
          wget https://get.helm.sh/helm-v3.10.2-linux-amd64.tar.gz
          tar -zxvf helm-v3.10.2-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
    
    - name: Add Helm Charts
      run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add influx  https://helm.influxdata.com/ 
          helm repo add grafana https://grafana.github.io/helm-charts
          
    - name: Helm Template Test
      run: |
            pwd
            ls
            cd cloud/kubernetes/helm
            helm dep up
            cd ../tests/template
            go test -v ./...
